Repository AY2223S1-CS2113-W12-1/tp, pull requests merged in 2022-11, with the labels that each got.

#221 Refactor all files with javadocs and fix all checkstyle checks
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/item/AddItemCommand.java
  src/main/java/seedu/duke/command/item/FindItemCommand.java
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/command/item/UpdateItemCommand.java
  src/main/java/seedu/duke/command/item/ViewItemCommand.java
  src/main/java/seedu/duke/command/transaction/AddTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/UpdateTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/ViewBorrowTransactionsByUserCommand.java
  src/main/java/seedu/duke/command/transaction/ViewLendTransactionsByUserCommand.java
  src/main/java/seedu/duke/command/transaction/ViewTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/ViewTransactionsByStatusCommand.java
  src/main/java/seedu/duke/command/user/AddUserCommand.java
  src/main/java/seedu/duke/command/user/FindUserCommand.java
  src/main/java/seedu/duke/command/user/RemoveUserCommand.java
  src/main/java/seedu/duke/command/user/ViewUserCommand.java
  src/main/java/seedu/duke/command/user/ViewUserGainCommand.java
  src/main/java/seedu/duke/command/user/ViewUserItemsCommand.java
  src/main/java/seedu/duke/command/user/ViewUserLossCommand.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
  src/main/java/seedu/duke/item/Item.java
  src/main/java/seedu/duke/item/ItemList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/storage/ItemStorage.java
  src/main/java/seedu/duke/storage/TransactionStorage.java
  src/main/java/seedu/duke/storage/UserStorage.java
  src/main/java/seedu/duke/transaction/Transaction.java
  src/main/java/seedu/duke/transaction/TransactionList.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/storage/ItemStorageTest.java
  src/test/java/seedu/duke/storage/TransactionStorageTest.java
  src/test/java/seedu/duke/transaction/TransactionListTest.java
  src/test/java/seedu/duke/transaction/TransactionTest.java
Labels: type.Enhancement

#224 Add architecture
  docs/DeveloperGuide.md
  docs/diagrams/architecture.puml
  docs/images/architecture.png
Labels: type.Enhancement

#225 added instructions for manual testing
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#228 Improve SLAP in main and enhance storage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/storage/StorageClass.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/TransactionStorage.java
  src/main/java/seedu/duke/transaction/TransactionList.java
Labels: type.Enhancement

#234 Add PPP for winston
  docs/team/winston.md
Labels: type.Enhancement

#242 added tests for userList
  src/test/java/seedu/duke/user/UserListTest.java
Labels: priority.Medium
