Repository AY2223S1-CS2113-W12-1/tp, pull requests merged in 2022-10, with the labels that each got.

#37 Refactor to fix checkstyle checks
  src/main/java/seedu/duke/exception/ExceptionHandler.java
  src/main/java/seedu/duke/exception/NullPointerException.java
  src/test/java/seedu/duke/user/UserListTest.java
Labels: type.Bug

#60 Add storage feature for transaction
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exception/ExceptionMessages.java
  src/main/java/seedu/duke/exception/StoreFailureException.java
  src/main/java/seedu/duke/exception/TransactionFileNotFoundException.java
  src/main/java/seedu/duke/parser/Command.java
  src/main/java/seedu/duke/storage/FilePath.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/TransactionStorage.java
  src/main/java/seedu/duke/transaction/Transaction.java
  src/main/java/seedu/duke/transaction/TransactionList.java
Labels: type.Task, priority.High

#94 Update User Guide
  docs/UserGuide.md
Labels: priority.Medium

#108 Fix CommandDesign uml
  docs/DeveloperGuide.md
  docs/diagrams/command/CommandDesign.puml
Labels: type.Bug

#113 Add UG/DG text and diagrams for update related commands'
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/item/UpdateItemSequence.puml
  docs/diagrams/transaction/UpdateTransactionSequence.puml
  docs/images/UpdateItemSequence.png
  docs/images/UpdateTransactionSequence.png
Labels: type.Enhancement

#114 Fix/find related commands
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/item/AddItemCommand.java
  src/main/java/seedu/duke/command/item/FindItemCommand.java
  src/main/java/seedu/duke/command/transaction/UpdateTransactionCommand.java
  src/main/java/seedu/duke/command/user/AddUserCommand.java
  src/main/java/seedu/duke/command/user/RemoveUserCommand.java
  src/main/java/seedu/duke/command/user/ViewUserCommand.java
  src/main/java/seedu/duke/item/ItemList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/transaction/Transaction.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/user/UserList.java
  src/test/java/seedu/duke/transaction/TransactionListTest.java
Labels: type.Enhancement, type.Bug

#115 added filter by category under sort-items command
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/item/Item.java
Labels: type.Enhancement

#124 Clean code for v2.0
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/exit/ExitCommand.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/item/AddItemCommand.java
  src/main/java/seedu/duke/command/item/ListCategoriesCommand.java
  src/main/java/seedu/duke/command/item/RemoveItemCommand.java
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/command/item/ViewItemCommand.java
  src/main/java/seedu/duke/command/transaction/AddTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/RemoveTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/UpdateTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/ViewTransactionsByStatusCommand.java
  src/main/java/seedu/duke/command/user/AddUserCommand.java
  src/main/java/seedu/duke/command/user/RemoveUserCommand.java
  src/main/java/seedu/duke/id/IdGenerator.java
  src/main/java/seedu/duke/item/Category.java
  src/main/java/seedu/duke/item/ItemList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/storage/FilePath.java
  src/main/java/seedu/duke/storage/ItemStorage.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/TransactionStorage.java
  src/main/java/seedu/duke/storage/UserStorage.java
  src/main/java/seedu/duke/transaction/Transaction.java
  src/main/java/seedu/duke/transaction/TransactionList.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/user/User.java
  src/main/java/seedu/duke/user/UserList.java
  src/test/java/seedu/duke/id/IdGeneratorTest.java
  src/test/java/seedu/duke/parser/DateParserTest.java
  src/test/java/seedu/duke/storage/ItemStorageTest.java
  src/test/java/seedu/duke/storage/TransactionStorageTest.java
  src/test/java/seedu/duke/storage/UserStorageTest.java
  src/test/java/seedu/duke/transaction/TransactionListTest.java
  src/test/java/seedu/duke/transaction/TransactionTest.java
Labels: priority.High

#125 v2.0 final
  docs/DeveloperGuide.md
Labels: priority.High

#130 Handle exception when files are edited
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
  src/main/java/seedu/duke/storage/ItemStorage.java
  src/main/java/seedu/duke/storage/TransactionStorage.java
  src/main/java/seedu/duke/storage/UserStorage.java
Labels: type.Bug, severity.Medium

#132 Enhance Storage
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: type.Enhancement

#133 Limit price range
  docs/UserGuide.md
  src/main/java/seedu/duke/command/item/AddItemCommand.java
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/command/item/UpdateItemCommand.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
Labels: type.Enhancement

#185 Fix UG typo and grammars and bug in add-tx command
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/item/AddItemCommand.java
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/command/transaction/AddTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/UpdateTransactionCommand.java
  src/main/java/seedu/duke/command/transaction/ViewTransactionsByUserCommand.java
  src/main/java/seedu/duke/command/user/ViewUserDebtCommand.java
  src/main/java/seedu/duke/exception/InvalidTransactionException.java
  src/main/java/seedu/duke/exception/message/ExceptionMessages.java
  src/main/java/seedu/duke/transaction/Transaction.java
  src/main/java/seedu/duke/transaction/TransactionList.java
  src/test/java/seedu/duke/transaction/TransactionListTest.java
Labels: type.Enhancement, priority.High

#202 Updated UG, DG and help command to include view-user-items
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/command/help/HelpCommand.java
Labels: priority.High, severity.Medium

#212 Refactor HelpCommand
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement

#217 Added PPP and tweaks to DG
  docs/DeveloperGuide.md
  docs/diagrams/user/ViewUserSequence.puml
  docs/images/ViewUserSequence.png
  docs/team/chiewyx.md
  src/main/java/seedu/duke/command/user/ViewUserItemsCommand.java
Labels: type.Task, priority.Medium

#218 refactored code based on comments
  docs/diagrams/item/SortItemsSequence.puml
  docs/images/SortItemsSequence.png
  src/main/java/seedu/duke/command/item/SortItemCommand.java
  src/main/java/seedu/duke/command/user/ViewUserItemsCommand.java
Labels: type.Enhancement, priority.Medium
